export type Role = 'generator' | 'consumer' | 'storage' | 'converter'
export type Category = Role
export type CurrentType = 'ac' | 'dc'

export interface Source { id?: string; type: 'manufacturer_datasheet' | 'manufacturer_product_page' | 'official_manual' | 'certification_document' | 'scientific_publication' | 'measurement' | 'reference'; title: string; url: string; accessed: string; page?: number | null; notes?: string }
export interface Quality { level: 'manufacturer_specification' | 'independently_measured' | 'estimated' | 'demonstration'; confidence: 'high' | 'medium' | 'low' }
export interface Port { type: CurrentType; nominalVoltageV?: number | null; minimumVoltageV?: number | null; maximumVoltageV?: number | null; maximumCurrentA?: number | null; frequencyHz?: number | null; continuousPowerW?: number | null; peakPowerW?: number | null; peakDurationSeconds?: number | null }
export interface Efficiency { nominal?: number | null; curve?: { loadPercent: number; efficiency: number }[] }
export interface Electrical { ratedPowerW?: number | null; nominalVoltageV?: number | null; minimumVoltageV?: number | null; maximumVoltageV?: number | null; openCircuitVoltageV?: number | null; maximumPowerVoltageV?: number | null; ratedCurrentA?: number | null; shortCircuitCurrentA?: number | null; maximumPowerCurrentA?: number | null; nominalCurrentA?: number | null; continuousPowerW?: number | null; startupPowerW?: number | null; startupDurationSeconds?: number | null; standbyPowerW?: number | null; frequencyHz?: number | null; powerFactor?: number | null; inputType?: CurrentType; outputType?: CurrentType; nominalCapacityAh?: number | null; nominalCapacityWh?: number | null; usableCapacityWh?: number | null; maximumChargeCurrentA?: number | null; maximumContinuousDischargeCurrentA?: number | null; maximumPeakDischargeCurrentA?: number | null; maximumPeakDischargeDurationSeconds?: number | null; maximumChargePowerW?: number | null; maximumContinuousDischargePowerW?: number | null; input?: Port; output?: Port; efficiency?: Efficiency; mpptMinimumVoltageV?: number | null; mpptMaximumVoltageV?: number | null; maximumPvVoltageV?: number | null; maximumPvCurrentA?: number | null }
export interface Operation { typicalDailyEnergyWh?: number | null; energyPerCycleWh?: number | null; maximumDepthOfDischargePercent?: number | null; chargeEfficiency?: number | null; dischargeEfficiency?: number | null; selfDischargePercentPerMonth?: number | null; productionProfile?: { type: 'user_defined' | 'solar' | 'constant'; capacityFactorPercent?: number } }
export interface Component { schemaVersion: '1.0'; id: string; manufacturer: string; model: string; name: string; category: Category; roles: Role[]; description: string; generatorType?: string; consumerType?: string; storageType?: string; converterType?: string; chemistry?: string; electrical: Electrical; operation: Operation; sources: Source[]; notes: string[]; dataQuality: Quality }

export type Day = 'monday'|'tuesday'|'wednesday'|'thursday'|'friday'|'saturday'|'sunday'
export type Usage = { mode: 'always' } | { mode: 'time_window'; start: string; end: string; daysOfWeek: Day[] } | { mode: 'duration'; hoursPerDay: number; activationsPerDay: number } | { mode: 'duty_cycle'; dutyCyclePercent: number; startupEventsPerHour: number } | { mode: 'profile'; resolutionMinutes: number; valuesW: number[] } | { mode: 'production'; capacityFactorPercent: number }
export interface SelectedComponent { instanceId: string; componentId: string; quantity: number; usage: Usage }
export interface SimulationSettings { durationHours: 24|48|168; resolutionMinutes: 1|5|15|60; initialSocPercent: number; minimumSocPercent: number; maximumSocPercent: number }
export interface SystemConfiguration { configurationVersion: '1.0'; applicationVersion: string; name: string; createdAt: string; simulation: SimulationSettings; components: SelectedComponent[]; assumptions?: { defaultConverterEfficiency?: number } }
export type Status = 'compatible'|'marginal'|'incompatible'|'unknown'
export interface CompatibilityResult { status: Status; code: string; message: string; componentIds: string[] }
export interface TimePoint { hour: number; generationW: number; demandW: number; batteryChargeW: number; batteryDischargeW: number; socPercent: number; unusedW: number; unmetW: number; lossesW: number; overload: boolean }
export interface SimulationResult { points: TimePoint[]; compatibility: CompatibilityResult[]; totals: { generationWh: number; demandWh: number; unmetWh: number; unusedWh: number; lossesWh: number; minSocPercent: number; maxSocPercent: number; maxLoadW: number; overloadEvents: number; runtimeHours: number|null }; consumerEnergy: { name: string; energyWh: number }[]; assumptions: string[] }
